# Advanced Assignment 22

Q.1.

The built-in array package helps in efficient representation of numeric values such as integers, floats, doubles and characters. Since only a single type of element is stored in an array, the elements have same size and hence can be accessed faster in memory.

Q.2.

Array object can store only one type of element throughout the array. Also, array can store only numeric values and characters.

Q.3.

Array package arrays and numpy arrays both store only one type of element throughout the array. Numpy arrays provide a lot more functionality for numerical computations. They can be used easily to process matrices which can be part of image processing tasks. Array package does not provide such computations. But it is much more lightweight and is faster than numpy array.

Q.4.

numpy.ones initializes an array of given shape with all elements having value as 1.
numpy.zeros initializes an array of given shape with all elements having value as 0.
numpy.empty initializes an array of given shape with arbitrary values for each element. If we have a user-defined class and initialize a numpy.empty array, all its values will be set to None.

In [1]:
import numpy as np

In [38]:
a = np.empty((2,3),dtype=int)
a

array([[-803475568,        694,          0],
       [         0,     131074,    7536751]])

In [23]:
class A:
    pass

In [37]:
np.empty((2,3), dtype=A)

array([[None, None, None],
       [None, None, None]], dtype=object)

In [35]:
np.empty(2)

array([1.07533215e-116, 4.50367904e+088])

Q.5.

numpy.fromfunction(function, shape, dtype)

This applies the function to each coordinate position of the element in the array. e.g. the first element of a 2D array has the coordinates (0,0). SO , the function will have 2 arguments. The first argument is an array of the x coordinates, the second argument is an array of the y coordinates.
E.g. we can find the diagnonal elements

In [109]:
np.fromfunction(lambda x,y: x == y, (size+1, size+1), dtype=int)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

Q.6.

The scalar value is added to all the elements of the array

In [111]:
l = np.ones((2,2)) + 10
l

array([[11., 11.],
       [11., 11.]])

Q.7.

Yes. The new scalar quantity is added to each element of the array.

In [112]:
l += 13

In [113]:
l

array([[24., 24.],
       [24., 24.]])

In [114]:
l *= 2

In [115]:
l

array([[48., 48.],
       [48., 48.]])

Q.8.

Strings have dtype U i.e. unicode inside numpy arrays. Numpy arrays can have variable length strings. The length of the longest string decides the dtype. If it is 3, then dtype is U3.

Q.9.

Addition/multiplication of numpy arrays is done by adding/multiplying corresponding elments. The constraint is that both arrays should have the same shape.

In [140]:
l1 = (np.ones((2,3))+1)
l2 = np.ones((2,3))
print(l1)
print(l2)

[[2. 2. 2.]
 [2. 2. 2.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [141]:
l1 + l2

array([[3., 3., 3.],
       [3., 3., 3.]])

In [142]:
l1 * l2

array([[2., 2., 2.],
       [2., 2., 2.]])

Q.10.

If we want to mask the values based on the values of the elements, we can use comparison operators to check the values and mask them using np.ma.masked_array.

In [164]:
l = [[1,2,3], [4,5,6], [7,8,9]]
l = np.array(l)
l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [153]:
mask = (l % 2 == 0)
mask

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [156]:
l_masked = np.ma.masked_array(l, mask, fill_value=0)
l_masked

masked_array(
  data=[[1, --, 3],
        [--, 5, --],
        [7, --, 9]],
  mask=[[False,  True, False],
        [ True, False,  True],
        [False,  True, False]],
  fill_value=0)

In [162]:
l_masked.compressed() # returning a 1d array of the unmasked values

array([1, 3, 5, 7, 9])

In [165]:
l_masked.filled(0) # filling masked values with 0

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

Q.11.



In [169]:
import random

In [196]:
from statistics import variance

In [192]:
from time import time

In [180]:
a = [random.random() * i for i in range(1000)]
a[:5]

[0.0,
 0.10220036586644399,
 1.3876081047812705,
 0.6730559667438452,
 3.6155437606097287]

In [187]:
def var(x):
    m = sum(x)/len(x)
    return sum([(i - m) ** 2 for i in x])/len(x)

In [200]:
print("Standard python")
before = time()
print(var(a))
after = time()
print("Time taken: ", after - before)
print("\nNumpy var function")
before = time()
print(np.var(np.array(a)))
after = time()
print("Time taken: ", after - before)
print("\nStatistics variance function")
before = time()
print(variance(a))
after = time()
print("Time taken: ", after - before)


Standard python
48838.41253740605
Time taken:  0.0009989738464355469

Numpy var function
48838.41253740611
Time taken:  0.0009970664978027344

Statistics variance function
48887.29983724334
Time taken:  0.010970830917358398


Here, time taken: variance() < np.var() < var()

Q.12.

The dimension of the boolean masked array is same as the original array. If we want to get only the unmasked values from it, we get a 1 dimensional array of the unmasked values, by using the compressed function of np.ma.masked_array.